library/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import UserViewSet, AuthorViewSet, BookViewSet, OrderViewSet, UserOrderViewSet

router = DefaultRouter()
router.register('user', UserViewSet)
router.register('order', OrderViewSet)
router.register('book', BookViewSet)
router.register('author', AuthorViewSet)
# urlpatterns = [
#     path('user/', UserViewSet.as_view({'get': 'list', 'post': 'create'}), name='user-list'),
#     path('user/<int:pk>/', UserViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='user-detail'),
#
    # path('user/<int:user_id>/order/', UserOrderViewSet.as_view({'get': 'list', 'post': 'create'}), name='user-order-list'),
    # path('user/<int:user_id>/order/<int:pk>/', UserOrderViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='user-order-detail'),
#
#     path('order/', OrderViewSet.as_view({'get': 'list', 'post': 'create'}), name='order-list'),
#     path('order/<int:pk>/', OrderViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='order-detail'),
#
#     path('book/', BookViewSet.as_view({'get': 'list', 'post': 'create'}), name='book-list'),
#     path('book/<int:pk>/', BookViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='book-detail'),
#
#     path('author/', AuthorViewSet.as_view({'get': 'list', 'post': 'create'}), name='author-list'),
#     path('author/<int:pk>/', AuthorViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='author-detail'),
# ]

urlpatterns = [
    path('user/<int:user_id>/order/', UserOrderViewSet.as_view({'get': 'list', 'post': 'create'}),
         name='user-order-list'),

    path('user/<int:user_id>/order/<int:pk>/',
         UserOrderViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}),
         name='user-order-detail'),

    path('', include(router.urls))
]

library/book/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('search/', views.BookSearchView.as_view(), name='book_search'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('books/', include('book.urls')),
    path('authors/', include('author.urls')),
    path('orders/', include('order.urls')),
    path('users/', include('user.urls')),
    path('403/', TemplateView.as_view(template_name='library/403.html'), name='403'),
    path('api/v1/', include('api.urls')),
]

library/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.UserListView.as_view(), name='user_list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
]

library/user/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from book.models import Book
from authentication.models import CustomUser


@method_decorator(login_required, name='dispatch')
class UserListView(ListView):
    model = CustomUser
    context_object_name = "user_list"
    template_name = 'user/user_list.html'
    ordering = ['email']


@method_decorator(login_required, name='dispatch')
class UserDetailView(DetailView):
    model = CustomUser
    context_object_name = "user"
    template_name = 'user/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        books = Book.objects.filter(order__user=user)
        context['books'] = books
        return context

library/user/templates/user/user_detail.html
{% extends 'authentication/base.html' %}

{% block page_header %}
<p>User</p>
{% endblock page_header %}

{% block content %}

<div class="card mb-3">
    <p class="card-header">Email: {{ user.email }}</p>
    <p class="card-body">First Name: {{ user.first_name|default:'---' }}</p>
    <p class="card-body">Middle Name: {{ user.middle_name|default:'---' }}</p>
    <p class="card-body">Last Name: {{ user.last_name|default:'---' }}</p>
    <p class="card-body">Registered: {{ user.created_at|default:'---' }}</p>
    {% if request.user.is_superuser %}
    <br>
    <h6>User Books</h6>
    <ul>

        {% for book in books %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.name }}</a></li>
        {% empty %}
            <li>No books found.</li>
        {% endfor %}
    {% endif %}
    </ul>
</div>
<h3><a href="{% url 'user:user_list'%}">Back</a></h3>
{% endblock content %}

library/user/templates/user/user_list.html
{% extends "authentication/base.html" %}

{% block page_header %}
<p>Books</p>
{% endblock page_header %}

{% block content %}
<ul>
    {% for user in user_list %}
    <li>
        <h3><a href="{% url 'user:user_detail' user.id %}">{{ user.email }}</a></h3>
    </li>
    {% empty %}
    <li><h3>No users have been added yet</h3></li>
    {% endfor %}
</ul>

{% endblock content %}